### ISSUE TITLE
Newest revision broke compatibility

### ISSUE THREAD

**Issue by reinhrst** [docker-library/python#134] opened 2016-08-03 13:44 UTC
PR #131 broke my build, not entirely sure why but probably related to other reports.

Smallest failing code:

    FROM python:3.5
    RUN apt-get update && apt-get install -y gconf2

**Comment by kevin-brown** [comment] 2016-08-03 14:25
This is most likely a duplicate of https://github.com/docker-library/python/issues/133.

**Comment by reinhrst** [comment] 2016-08-03 16:46
Yes, very likely same cause, however not sure since I get very different errors.

**Comment by ejain** [comment] 2016-08-03 22:32
Same error here: 
```
Errors were encountered while processing:
 gconf2
 libgnomevfs2-common
 libgnomevfs2-0:amd64
 libgnome2-common
 libgnome-2-0:amd64
 libgnome2-bin
 libgnome2-0:amd64
 libgnomevfs2-extra:amd64
E: Sub-process /usr/bin/dpkg returned an error code (1)
The command '/bin/sh -c apt-get update && apt-get -y install openjdk-7-jdk' returned a non-zero code: 100
```

**Comment by JayH5** [comment] 2016-08-04 07:43
This is the same as #133:
```
...
/var/lib/dpkg/info/gconf2.postinst: 45: /var/lib/dpkg/info/gconf2.postinst: gconf-schemas: not found
dpkg: error processing package gconf2 (--configure):
 subprocess installed post-installation script returned error exit status 127
Processing triggers for libc-bin (2.19-18+deb8u4) ...
Processing triggers for systemd (215-17+deb8u4) ...
Errors were encountered while processing:
 gconf2
E: Sub-process /usr/bin/dpkg returned an error code (1)
```

Try run `gconf-schemas`:
```
root@494c479df98d:/# gconf-schemas
bash: /usr/sbin/gconf-schemas: /usr/bin/python: bad interpreter: No such file or directory
```

**Comment by ryneeverett** [comment] 2016-08-06 17:43
This wouldn't be so bad if there weren't also issues with image backwards-compatibility preventing pinning older versions from dockerhub.

```console
$ docker --version
Docker version 1.12.0, build 8eab29e
$ docker images --digests --no-trunc | grep python
python    3.5    <none>    sha256:b61493a524315bc6d1b0c9e32b380bfecda30f3052fddf49130a264a048115b2    10 weeks ago    674.4 MB
$ docker pull python@sha256:b61493a524315bc6d1b0c9e32b380bfecda30f3052fddf49130a264a048115b2
Error response from daemon: manifest unknown: manifest unknown
```

**Closed** 2016-08-08 16:58 UTC
