### ISSUE TITLE
Docker 2.7.10 image issue

### ISSUE THREAD

**Issue by warren-methods** [docker-library/python#66] opened 2015-11-17 11:17 UTC
I can't seem to pull version 2.7.10 any more, I always get the following error:

Error downloading dependent layers 
Error pulling image (2.7.10) from docker.io/library/python, Driver aufs failed to create image rootfs dc921aeac8d06e7bd5b2d85b8684bb7c94ed08db3f18a9b6e897827810b289de: open /var/lib/docker/aufs/layers/4c0cc976b7bbefe9abdfd8f0aae1bb3759004d3c9888c3164b38909b862c0cdf: no such file or directory

It's happening on Docker hub builds too.

**Comment by oeuftete** [comment] 2015-11-17 20:17
From discussions in the docker IRC channel, this affects anyone using docker 1.9.0, the only officially supported version per https://hub.docker.com/_/python/ .  Other python images (I've seen `3.4.3`, others report `3.5.0`) have the same issue.

**Comment by nickjj** [comment] 2015-11-17 20:21
I'm seeing this happen with Docker 1.9 too. Docker 1.8.3 is working fine with the same image on Linux.

**Comment by density** [comment] 2015-11-18 02:12
@tianon interesting. that looks like it could have been it. so are we just completely out of luck until the fix is in? is there any way to push working versions of the python images? i'm sure a lot of people who depend on this to deploy are out of luck for now

**Comment by nickjj** [comment] 2015-11-18 13:01
I would take a peek at this too, https://github.com/docker/docker/issues/18008.

I can confirm with @oeuftete that 2.7.9 and 2.7.9-slim are both working with Docker 1.8.3 (probably 1.9 too but I didn't test first hand).

**Comment by tianon** [comment] 2015-11-19 00:32
I've tested again, and this seems to be working here, so I wonder if something changed on the Hub side?  Can anyone else confirm?

**Comment by nickjj** [comment] 2015-11-19 00:39
It's failing here with `python:2.7.10-slim` still while `python:2.7.9-slim `works as it did 12 hours ago.

Tested it on a fresh Debian Jessie host running Docker 1.8.3.

**Comment by oeuftete** [comment] 2015-11-19 02:09
I can now pull `python:2.7.10` with docker 1.9.0, but not `python:3.4.3`:

```text
Error pulling image (3.4.3) from docker.io/library/python, Driver aufs failed to create image rootfs dc921aeac8d06e7bd5b2d85b8684bb7c94ed08db3f18a9b6e897827810b289de: open /media/r0/var/lib/docker/aufs/layers/4c0cc976b7bbefe9abdfd8f0aae1bb3759004d3c9888c3164b38909b862c0cdf: no such file or directory
```

**Comment by yosifkit** [comment] 2015-11-19 21:23
We are working to roll back the build server to docker 1.8.3 and rebuild the images;  it'll take some time for it to complete.

**Comment by tianon** [comment] 2015-12-08 20:13
This is fixed now. :+1:

**Closed by tianon** 2015-12-08 20:13 UTC
