### ISSUE TITLE
`python:3.8` does not include `/usr/lib/python3/dist-packages` in `sys.path`

### ISSUE THREAD

**Issue by MarcelWaldvogel** [docker-library/python#482] opened 2020-05-10 18:28 UTC
The following Dockerfile fails with `ModuleNotFoundError`:
```Docker
FROM python:3.8
RUN apt update && apt install python3-urllib3
RUN python3 -c "import urllib3"
```
Adding `ENV PYTHONPATH=/usr/lib/python3/dist-packages` before the `python3` command will make it run smoothly. So it ignores libraries installed by `apt`, which is e.g. essential for `pygit2`, which cannot be reasonable installed with `pip`/`pip3`.

**Comment by wglambert** [comment] 2020-05-11 15:58
https://github.com/docker-library/python/issues/43#issuecomment-94095495

>I'm not sure I'm following for what's gained by supporting this path besides encouraging people to mix Debian Python packages with `pip install` packages? (which is generally considered harmful)

>I think if you're relying on Debian-packaged python dependencies, you're probably going to be better off going straight for either `FROM debian` or `FROM buildpack-deps` instead of trying to get this image to do what you might expect when mixing dependencies from APT and elsewhere.

https://packages.debian.org/buster/python3-urllib3
Python3 is a dependency, which will install Python from the Debian repo's alongside the image's compiled Python

**Comment by tianon** [comment] 2020-05-11 17:22
Closing as duplicate of https://github.com/docker-library/python/issues/43

**Closed by tianon** 2020-05-11 17:22 UTC
Labels: question

**Comment by MarcelWaldvogel** [comment] 2020-05-11 20:08
On ARM, `pip3 install pygit2` fails at compile-time, as it is missing `git2.h`. Trying to first `apt update && apt install libgit2-dev` fails, because, again at compile-time, a version mismatch between `libgit2-dev` (0.27.4) and `pygit2` (1.2.1) is detected. Including rules for selecting the appropriate pygit2 version is horrible, so requiring pygit2 along with other packages from pypi essentially requires mixing native packages and python packages.

But I might consider switching to `FROM debian`, even though multiarch building will be much slower then.
