### ISSUE TITLE
unused packages in python:3

### ISSUE THREAD

**Issue by jennolsen84** [docker-library/python#64] opened 2015-10-19 19:07 UTC
Seems like some space could be saved by adding an `apt-get autoremove` in the Dockerfiles for the non-slim images.

Also, on an unrelated note: python:3 still pull in 3.4.x instead of 3.5, is that expected?

```
$ docker run --rm -it python:3 bash
root@ffaf32c0f8b5:/# apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
The following packages will be REMOVED:
  gir1.2-freedesktop gir1.2-gdkpixbuf-2.0 gir1.2-glib-2.0 gir1.2-rsvg-2.0 libcairo-gobject2 libcairo-script-interpreter2 libcdt5 libcgraph6 libcroco3 libdjvulibre-dev libelfg0 libexif-dev libexif12
  libexpat1-dev libfontconfig1-dev libfreetype6-dev libgd3 libgirepository-1.0-1 libglib2.0-bin libgraphviz-dev libgvc6 libgvpr2 libice-dev libice6 libilmbase-dev libjasper-dev libjbig-dev libjs-excanvas
  libjs-jquery liblcms2-dev liblqr-1-0-dev liblzo2-2 libmagickcore-6-arch-config libmagickcore-6-headers libmagickwand-6-headers libopenexr-dev libpathplan4 libpcre3-dev libpcrecpp0 libpixman-1-dev
  libpthread-stubs0-dev librsvg2-2 librsvg2-common libsm-dev libsm6 libtiff5-dev libtiffxx5 libvpx1 libwmf-dev libx11-dev libxau-dev libxcb-render0-dev libxcb-shm0-dev libxcb1-dev libxdmcp-dev libxdot4
  libxext-dev libxpm4 libxrender-dev libxt-dev libxt6 mime-support pkg-config x11-common x11proto-core-dev x11proto-input-dev x11proto-kb-dev x11proto-render-dev x11proto-xext-dev xorg-sgml-doctools
  xtrans-dev
0 upgraded, 0 newly installed, 71 to remove and 0 not upgraded.
After this operation, 55.2 MB disk space will be freed.
Do you want to continue? [Y/n] n
```

**Comment by yosifkit** [comment] 2015-10-19 19:47
That wouldn't actually save space, since those are installed in previous layers of the image.  I think some are valid to keep because they are only autoremovable after we `apt-get purge -y python.*`.  Which is later installed directly from upstream, but not through a deb package, so apt doesn't know about it.

Yes, that is "expected", but needs to be updated.  We missed updating it when we moved from the beta 3.5 to the release (I'll go fix that).

**Comment by jennolsen84** [comment] 2015-10-19 23:06
ah, so ideally, the following would be done so that apt-get autoremove will not accidentally delete desired libraries (since they are wanted by python).

1) Create a debian package from python source
2) Install the newly created deb file
3) cleanup

(all in one layer)

I totally understand if this is not high on the priority list right now, but would you agree that it would be the best implementation?

**Comment by tianon** [comment] 2016-08-08 23:06
I think this was actually caused by https://github.com/docker-library/python/issues/129, and is thus finally really fixed by https://github.com/docker-library/python/pull/137:
```console
$ docker run -it --rm python:3 bash
root@160e5530f522:/# apt-get autoremove
Reading package lists... Done
Building dependency tree       
Reading state information... Done
0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.
```

**Comment by wglambert** [comment] 2018-05-02 21:26
This question/request seems resolved so I'm going to close it.

If you believe this to be in error then let me know and I'll re-open it

**Closed by wglambert** 2018-05-02 21:26 UTC
Labels: question
