### ISSUE TITLE
Alpine variant handles signals improperly

### ISSUE THREAD

**Issue by bronger** [docker-library/python#356] opened 2018-12-01 13:32 UTC
Compare
```console
$ docker run --rm python python3 -c 'import signal; signal.sigtimedwait(set(), 3600)'
^CTraceback (most recent call last):
  File "<string>", line 1, in <module>
KeyboardInterrupt
```
with
```console
$ docker run --rm python:alpine python3 -c 'import signal; signal.sigtimedwait(set(), 3600)'
^C
```

In other words, the Alpine Python ignores SIGINT for this code.

Expected behaviour is that also the Alpine variant exits with a `KeyboardInterrupt`.

**Comment by tianon** [comment] 2018-12-05 23:33
Have you pulled the latest image?  (This is a duplicate of https://github.com/docker-library/python/issues/328, which points to https://bugs.python.org/issue34004, which is closed as fixed.)

It appears to work properly here:

```console
$ docker pull python:3-alpine
3-alpine: Pulling from library/python
Digest: sha256:abc2a66d8ce0ddf14b1d51d4c1fe83f21059fa1c4952c02116cb9fd8d5cfd5c4
Status: Image is up to date for python:3-alpine

$ docker run --rm python:3-alpine python3 -c 'import signal; signal.sigtimedwait(set(), 3600)'
^CFatal Python error: init_sys_streams: can't initialize sys standard streams
Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 963, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 906, in _find_spec
  File "<frozen importlib._bootstrap_external>", line 1280, in find_spec
  File "<frozen importlib._bootstrap_external>", line 1252, in _get_spec
  File "<frozen importlib._bootstrap_external>", line 1391, in find_spec
  File "<frozen importlib._bootstrap_external>", line 59, in _path_join
  File "<frozen importlib._bootstrap_external>", line 59, in <listcomp>
KeyboardInterrupt
```

**Closed by tianon** 2018-12-05 23:33 UTC
Labels: Issue

**Comment by bronger** [comment] 2019-02-27 06:58
Have you tried my above commands? I re-pulled both images and still see this issue.

**Comment by yosifkit** [comment] 2019-02-27 19:55
@bronger, you are correct, the lock is not interruptible by signals in Alpine. I am not sure how @tianon's example worked (perhaps he pushed control-c too fast), but that doesn't really matter. This is a known python on Alpine (muslc) limitation.

> Changed in version 3.2: Lock acquisition can now be interrupted by signals on POSIX **if the underlying threading implementation supports it**.
>
> \- https://docs.python.org/3/library/threading.html (emphasis added)

See also the changesets on https://bugs.python.org/issue34004, (like https://github.com/python/cpython/commit/5b10d5111d7a855297654af9045f8907b7d3dd08)
