### ISSUE TITLE
Requesting a docker file for the Ubuntu or CENT OS

### ISSUE THREAD

**Issue by krishna3008** [docker-library/python#745] opened 2022-08-08 13:08 UTC
Is it possible to get a docker file for the UBUNTU or CENT OS

**Comment by wglambert** [comment] 2022-08-08 16:04
Duplicate of https://github.com/docker-library/python/issues/708 and possibly https://github.com/docker-library/golang/issues/392

**Closed** 2022-08-08 23:24 UTC
Labels: Request
