### ISSUE TITLE
pip fails on linux/arm64 due to missing lsb_release

### ISSUE THREAD

**Issue by bantu** [docker-library/python#625] opened 2021-07-01 10:59 UTC
### Files

Dockerfile:
```
FROM python:3.8
ENV PYTHONUNBUFFERED 1
COPY /setup.py .
RUN pip install -e .
```

setup.py
```
from setuptools import setup
setup(name='foo', version='1.0')
```

### Command

command
```
docker buildx create --driver=docker-container --use
docker buildx build --platform linux/amd64,linux/arm64 --file Dockerfile .
```

output
```
WARN[0000] No output specified for docker-container driver. Build result will only remain in the build cache. To push result image into registry use --push or to load image into docker use --load 
[+] Building 9.0s (11/11) FINISHED                                                                                                                                                            
 => [internal] load build definition from Dockerfile                                                                                                                                     0.1s
 => => transferring dockerfile: 31B                                                                                                                                                      0.0s
 => [internal] load .dockerignore                                                                                                                                                        0.1s
 => => transferring context: 2B                                                                                                                                                          0.0s
 => [linux/amd64 internal] load metadata for docker.io/library/python:3.8                                                                                                                0.5s
 => [linux/arm64 internal] load metadata for docker.io/library/python:3.8                                                                                                                0.5s
 => CACHED [linux/arm64 1/3] FROM docker.io/library/python:3.8@sha256:1c67caa564823e87b5729d57d96aa347b8ea3f7caee871da81b4c5b196620f4b                                                   0.0s
 => => resolve docker.io/library/python:3.8@sha256:1c67caa564823e87b5729d57d96aa347b8ea3f7caee871da81b4c5b196620f4b                                                                      0.1s
 => [internal] load build context                                                                                                                                                        0.1s
 => => transferring context: 97B                                                                                                                                                         0.0s
 => CACHED [linux/amd64 1/3] FROM docker.io/library/python:3.8@sha256:1c67caa564823e87b5729d57d96aa347b8ea3f7caee871da81b4c5b196620f4b                                                   0.0s
 => => resolve docker.io/library/python:3.8@sha256:1c67caa564823e87b5729d57d96aa347b8ea3f7caee871da81b4c5b196620f4b                                                                      0.1s
 => [linux/arm64 2/3] COPY /setup.py .                                                                                                                                                   0.3s
 => [linux/amd64 2/3] COPY /setup.py .                                                                                                                                                   0.3s
 => [linux/amd64 3/3] RUN pip install -e .                                                                                                                                               2.7s
 => ERROR [linux/arm64 3/3] RUN pip install -e .                                                                                                                                         7.6s
------                                                                                                                                                                                        
 > [linux/arm64 3/3] RUN pip install -e .:                                                                                                                                                    
#8 7.264 ERROR: Exception:                                                                                                                                                                    
#8 7.264 Traceback (most recent call last):                                                                                                                                                   
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 180, in _main                                                                                
#8 7.264     status = self.run(options, args)                                                                                                                                                 
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 205, in wrapper
#8 7.264     return func(self, options, args)
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 269, in run
#8 7.264     session = self.get_default_session(options)
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 77, in get_default_session
#8 7.264     self._session = self.enter_context(self._build_session(options))
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 87, in _build_session
#8 7.264     session = PipSession(
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 275, in __init__
#8 7.264     self.headers["User-Agent"] = user_agent()
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 132, in user_agent
#8 7.264     linux_distribution = distro.linux_distribution()  # type: ignore
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
#8 7.264     return _distro.linux_distribution(full_distribution_name)
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
#8 7.264     self.version(),
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 741, in version
#8 7.264     self.lsb_release_attr('release'),
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
#8 7.264     return self._lsb_release_info.get(attribute, '')
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 556, in __get__
#8 7.264     ret = obj.__dict__[self._fname] = self._f(obj)
#8 7.264   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
#8 7.264     stdout = subprocess.check_output(cmd, stderr=devnull)
#8 7.264   File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
#8 7.264     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#8 7.264   File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
#8 7.264     raise CalledProcessError(retcode, process.args,
#8 7.264 subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
#8 7.277 Traceback (most recent call last):
#8 7.277   File "/usr/local/bin/pip", line 8, in <module>
#8 7.278     sys.exit(main())
#8 7.279   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/main.py", line 71, in main
#8 7.279     return command.main(cmd_args)
#8 7.279   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 104, in main
#8 7.280     return self._main(args)
#8 7.280   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 221, in _main
#8 7.280     self.handle_pip_version_check(options)
#8 7.280   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 143, in handle_pip_version_check
#8 7.281     session = self._build_session(
#8 7.281   File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 87, in _build_session
#8 7.281     session = PipSession(
#8 7.281   File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 275, in __init__
#8 7.282     self.headers["User-Agent"] = user_agent()
#8 7.282   File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/session.py", line 132, in user_agent
#8 7.282     linux_distribution = distro.linux_distribution()  # type: ignore
#8 7.282   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 125, in linux_distribution
#8 7.283     return _distro.linux_distribution(full_distribution_name)
#8 7.283   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 681, in linux_distribution
#8 7.284     self.version(),
#8 7.284   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 741, in version
#8 7.285     self.lsb_release_attr('release'),
#8 7.285   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 903, in lsb_release_attr
#8 7.287     return self._lsb_release_info.get(attribute, '')
#8 7.287   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 556, in __get__
#8 7.288     ret = obj.__dict__[self._fname] = self._f(obj)
#8 7.288   File "/usr/local/lib/python3.8/site-packages/pip/_vendor/distro.py", line 1014, in _lsb_release_info
#8 7.289     stdout = subprocess.check_output(cmd, stderr=devnull)
#8 7.289   File "/usr/local/lib/python3.8/subprocess.py", line 415, in check_output
#8 7.290     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
#8 7.290   File "/usr/local/lib/python3.8/subprocess.py", line 516, in run
#8 7.291     raise CalledProcessError(retcode, process.args,
#8 7.291 subprocess.CalledProcessError: Command '('lsb_release', '-a')' returned non-zero exit status 1.
------
Dockerfile:4
--------------------
   2 |     ENV PYTHONUNBUFFERED 1
   3 |     COPY /setup.py .
   4 | >>> RUN pip install -e .
   5 |     
--------------------
error: failed to solve: rpc error: code = Unknown desc = executor failed running [/dev/.buildkit_qemu_emulator /bin/sh -c pip install -e .]: exit code: 1
```

**Comment by bantu** [comment] 2021-07-01 11:21
pip does not depend on lsb_release as it has code to ignore the case in which the lsb_release command is not found. See https://github.com/pypa/pip/blame/fc394ca52b84bcc04c48817b1e874bd392ca98c6/src/pip/_vendor/distro.py#L1011

In the output shown above, the lsb_release command is actually invoked, but exists with non-zero status.

**Comment by tianon** [comment] 2021-07-01 19:00
I can't reproduce: :confused:

```console
$ docker build --platform linux/arm64/v8 --pull .
Sending build context to Docker daemon   1.01GB
Step 1/4 : FROM python:3.8
3.8: Pulling from library/python
310b368da982: Already exists 
86422c44ee00: Pull complete 
9137877e0c26: Pull complete 
785171b903c4: Pull complete 
0373cebfde2c: Pull complete 
c841dd70245b: Pull complete 
cf7f0da16185: Pull complete 
3d7b67a60a9d: Pull complete 
fc624a25fd40: Pull complete 
Digest: sha256:1c67caa564823e87b5729d57d96aa347b8ea3f7caee871da81b4c5b196620f4b
Status: Downloaded newer image for python:3.8
 ---> 5b044e303f03
Step 2/4 : ENV PYTHONUNBUFFERED 1
 ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in ff3a208263ee
Removing intermediate container ff3a208263ee
 ---> 9c5da4700439
Step 3/4 : COPY /setup.py .
 ---> 06995bd07582
Step 4/4 : RUN pip install -e .
 ---> [Warning] The requested image's platform (linux/arm64) does not match the detected host platform (linux/amd64) and no specific platform was requested
 ---> Running in 92690ea13930
Obtaining file:///
Installing collected packages: foo
  Running setup.py develop for foo
Successfully installed foo-1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
Removing intermediate container 92690ea13930
 ---> edafbc2d76f1
Successfully built edafbc2d76f1
```

**Comment by bantu** [comment] 2021-07-01 19:02
@tianon Thanks for trying. I think in that case, this might be caused by the emulation logic of buildx. Does that make sense?

**Comment by bantu** [comment] 2021-07-01 19:08
There we go: https://github.com/docker/buildx/issues/493 Please excuse the noise.

**Comment by tianon** [comment] 2021-07-01 19:11
It's certainly possible, but I'm testing on a system that can only run that image thanks to https://packages.debian.org/bullseye/qemu-user-static so it seems odd for that to be the culprit?  It seems worth trying to reproduce interactively instead to try narrowing down what's wrong with your specific setup (ie, something like `docker run --rm --platform linux/arm64/v8 python:3.8 lsb_release -a`), which should look like this:

```console
$ docker run --rm --platform linux/arm64/v8 python:3.8 lsb_release -a
docker: Error response from daemon: OCI runtime create failed: container_linux.go:380: starting container process caused: exec: "lsb_release": executable file not found in $PATH: unknown.
```

:sweat_smile:

**Comment by bantu** [comment] 2021-07-01 19:16
@tianon I can provide some more details:

The buildx command were executed using image `docker:20.10.7` via GitLab CI.

**Comment by tianon** [comment] 2021-08-20 23:50
Sorry -- I'm going to close this because there's really not much more we can do to help. :sweat_smile:

**Closed by tianon** 2021-08-20 23:50 UTC
