### ISSUE TITLE
Unable to build docker images using python:3 tag

### ISSUE THREAD

**Issue by manideepdebbeti** [docker-library/python#846] opened 2023-06-28 02:54 UTC
Hi,

I was using python:3 as base image to build a custom docker image. Till last week it was working fine and from yesterday I was unable to build the image as it is throwing the below error. It is failing at apt-get update command.
```
#7 [3/6] RUN apt-get update && apt-get install -y jq
#7 30.91 Ign:1 http://deb.debian.org/debian bookworm InRelease
#7 60.93 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
#7 90.96 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
#7 121.0 Ign:1 http://deb.debian.org/debian bookworm InRelease
#7 151.0 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
#7 181.0 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
#7 211.1 Ign:1 http://deb.debian.org/debian bookworm InRelease
#7 241.1 Ign:2 http://deb.debian.org/debian bookworm-updates InRelease
#7 271.1 Ign:3 http://deb.debian.org/debian-security bookworm-security InRelease
#7 301.2 Err:1 http://deb.debian.org/debian bookworm InRelease
#7 301.2   Temporary failure resolving 'deb.debian.org'
#7 331.2 Err:2 http://deb.debian.org/debian bookworm-updates InRelease
#7 331.2   Temporary failure resolving 'deb.debian.org'
#7 361.2 Err:3 http://deb.debian.org/debian-security bookworm-security InRelease
#7 361.2   Temporary failure resolving 'deb.debian.org'
#7 361.2 Reading package lists...
#7 361.3 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm/InRelease  Temporary failure resolving 'deb.debian.org'
#7 361.3 W: Failed to fetch http://deb.debian.org/debian/dists/bookworm-updates/InRelease  Temporary failure resolving 'deb.debian.org'
#7 361.3 W: Failed to fetch http://deb.debian.org/debian-security/dists/bookworm-security/InRelease  Temporary failure resolving 'deb.debian.org'
#7 361.3 W: Some index files failed to download. They have been ignored, or old ones used instead.
#7 361.3 Reading package lists...
#7 361.3 Building dependency tree...
#7 361.3 Reading state information...
#7 361.3 E: Unable to locate package jq
#7 ERROR: process "/bin/sh -c apt-get update && apt-get install -y jq" did not complete successfully: exit code: 100
```
Dockerfile
```
FROM python:3
WORKDIR /usr/src/app
RUN apt-get update && apt-get install -y jq
COPY requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt
COPY . .
ENTRYPOINT ["python", "-b"]
```
I tried using multiple python images with tags latest, bookworm etc but still facing same issue.

**Comment by tianon** [comment] 2023-06-28 16:58
I think this is a duplicate of #837

(So you'll want to update libseccomp2, Docker, and runc on your host, and using the older `bullseye` images explicitly is a reasonable temporary workaround)

**Comment by manideepdebbeti** [comment] 2023-06-28 23:55
@tianon I tried using the alternatives #837 but facing the same issue

**Comment by tianon** [comment] 2023-12-15 00:42
I'm sorry, but this is definitely an environmental issue, not something in the image (ie, not something we could fix via an image update), so I think for anything further you'll need to do some debugging of your environment (for example, testing whether other Debian Bookworm-based images have the same issue performing `apt-get update`, whether `--security-opt seccomp=unconfined` resolves it, etc and thus narrow down what the actual proper fix is).

**Closed by tianon** 2023-12-15 00:42 UTC
