### ISSUE TITLE
Not able to build latest docker:3.8 image on Docker 20.10.7

### ISSUE THREAD

**Issue by umang-agrawal** [docker-library/python#843] opened 2023-06-22 07:26 UTC
Not able to build latest docker:3.8 image on Docker 20.10.7 

Sample Dockerfile
```
FROM python:3.8
COPY requirements.txt /app/
WORKDIR /app
RUN pip install -r requirements.txt
```

requirements.txt 
```
Flask==2.0.1
numpy==1.18.1
pandas==1.0.1
redis==4.3.1
pyarrow==6.0.0
connexion[swagger-ui] == 2.14.2
swagger-ui-bundle == 0.0.9
setuptools == 57.5.0
python_dateutil == 2.8.2
```

Its failing with error:
```
18:08:41    Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
18:08:41  ERROR: Exception:
18:08:41  Traceback (most recent call last):
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 160, in exc_logging_wrapper
18:08:41      status = run_func(*args)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/req_command.py", line 247, in wrapper
18:08:41      return func(self, options, args)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 419, in run
18:08:41      requirement_set = resolver.resolve(
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/resolver.py", line 92, in resolve
18:08:41      result = self._result = resolver.resolve(
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 481, in resolve
18:08:41      state = resolution.resolve(requirements, max_rounds=max_rounds)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 348, in resolve
18:08:41      self._add_to_criteria(self.state.criteria, r, parent=None)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/resolvers.py", line 172, in _add_to_criteria
18:08:41      if not criterion.candidates:
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/resolvelib/structs.py", line 151, in __bool__
18:08:41      return bool(self._sequence)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 155, in __bool__
18:08:41      return any(self)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 143, in <genexpr>
18:08:41      return (c for c in iterator if id(c) not in self._incompatible_ids)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/found_candidates.py", line 47, in _iter_built
18:08:41      candidate = func()
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/factory.py", line 206, in _make_candidate_from_link
18:08:41      self._link_candidate_cache[link] = LinkCandidate(
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 297, in __init__
18:08:41      super().__init__(
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 162, in __init__
18:08:41      self.dist = self._prepare()
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 231, in _prepare
18:08:41      dist = self._prepare_distribution()
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/resolution/resolvelib/candidates.py", line 308, in _prepare_distribution
18:08:41      return preparer.prepare_linked_requirement(self._ireq, parallel_builds=True)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 491, in prepare_linked_requirement
18:08:41      return self._prepare_linked_requirement(req, parallel_builds)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 536, in _prepare_linked_requirement
18:08:41      local_file = unpack_url(
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 166, in unpack_url
18:08:41      file = get_http_url(
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/operations/prepare.py", line 107, in get_http_url
18:08:41      from_path, content_type = download(link, temp_dir.path)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/network/download.py", line 147, in __call__
18:08:41      for chunk in chunks:
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_internal/cli/progress_bars.py", line 52, in _rich_progress_bar
18:08:41      with progress:
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/rich/progress.py", line 1169, in __enter__
18:08:41      self.start()
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/rich/progress.py", line 1160, in start
18:08:41      self.live.start(refresh=True)
18:08:41    File "/usr/local/lib/python3.8/site-packages/pip/_vendor/rich/live.py", line 132, in start
18:08:41      self._refresh_thread.start()
18:08:41    File "/usr/local/lib/python3.8/threading.py", line 852, in start
18:08:41      _start_new_thread(self._bootstrap, ())
18:08:41  RuntimeError: can't start new thread
```

**To make it work i have to use pyhthon:3.8 with `sha256:c71276c7380995f2c0a0c43ca18cdec181b764fd56a7ae5efa603a3f6b9e4c4b` dated 23rd May 2023.** 
Looks like some recent changes caused this issue. 

Can someone please help? 
Thanks in advance.

**Comment by tianon** [comment] 2023-06-22 19:23
This looks to me like a duplicate of https://github.com/docker-library/python/issues/835

You'll want to update Docker (and libseccomp2 / runc) on your host.

**Comment by yosifkit** [comment] 2023-07-20 21:27
Closing as Duplicate. (See also https://github.com/docker-library/python/issues/837#issuecomment-1599640563)

**Closed by yosifkit** 2023-07-20 21:27 UTC
