### ISSUE TITLE
Python 3.8.6 has an incompatibility with gevent and gunicorn

### ISSUE THREAD

**Issue by AaronFriel** [docker-library/python#520] opened 2020-09-25 01:29 UTC
When using the `python:3.8` image, gunicorn and gevent do not play nice and infinite loop.

**Comment by tianon** [comment] 2020-09-25 01:46
Do you have an example command / Dockerfile we can use to reproduce?

**Comment by AaronFriel** [comment] 2020-09-25 01:55
Closed source unfortunately - it looks like a very recent (today) change to `python:3.8` caused an old version of gevent (1.4.0) to break.

Apparently 1.4.0 was never tested on 3.8 so this compatibility was always suspicious and untested - so that's not ideal.

**Comment by AaronFriel** [comment] 2020-09-25 01:55
If anyone else hits this issue or this issue: https://github.com/gevent/gevent/issues/1679

The resolution is to update gevent to a modern version, we used `20.9.0` and that resolved it.

**Comment by tianon** [comment] 2020-09-25 18:29
Ah, so this is an upstream Python / gevent incompatibility?  (and we can close this issue?)

**Comment by AaronFriel** [comment] 2020-09-25 19:08
I'm not sure, I think so. You might see other people find this issue over the next few days.

**Comment by tianon** [comment] 2020-09-25 19:09
Ok, sounds good; since there's nothing we can do to fix this in the image, I'm going to close.

Hopefully other users running into the same will find this thread. 👍

**Closed by tianon** 2020-09-25 19:09 UTC
