### ISSUE TITLE
python:3.8-alpine ignores site packages

### ISSUE THREAD

**Issue by traverseda** [docker-library/python#601] opened 2021-04-04 17:39 UTC
```Dockerfile
FROM python:3.8-alpine

RUN apk add --no-cache python3 py3-cryptography py3-pip py3-virtualenv

RUN python3 -m venv --system-site-packages venv
RUN venv/bin/pip install --no-cache-dir authlib
```

Is broken, it doesn't use the site-packages level py3-cryptography.

```Dockerfile
FROM alpine:3.13

RUN apk add --no-cache python3 py3-cryptography py3-pip py3-virtualenv

RUN python3 -m venv --system-site-packages venv
RUN venv/bin/pip install --no-cache-dir authlib
```

Works

**Comment by tianon** [comment] 2021-04-05 16:53
This is conceptually a duplicate of #594 -- when you install any Python-related package from the package manager, you'll be installing a second (incompatible) version of Python.  If you want your installed modules to be compatible with the Python included in this image, I would recommend you install them exclusively via `pip`.

**Closed** 2021-04-05 16:53 UTC

**Comment by traverseda** [comment] 2021-04-05 17:04
Oh, that's a pretty big problem since a lot of packages need to be re-compiled for mucl-libc based distros. Thankfully the easy work around is to use base alpine instead.
