### ISSUE TITLE
no match for platform in manifest: not found

### ISSUE THREAD

**Issue by escherstair** [docker-library/python#987] opened 2024-10-23 14:59 UTC
I tried to use
`FROM arm64v8/python:3.11.10-slim-bookworm`
as base image for my container, but I got the following error

> failed to solve: arm64v8/python:3.11.10-slim-bookworm: failed to resolve source metadata for docker.io/arm64v8/python:3.11.10-slim-bookworm: no match for platform in manifest: not found

In the past I've used
`FROM arm64v8/python:3.11.0-alpine`
and everything worked fine.

What could be the problem?

**Comment by yosifkit** [comment] 2024-10-23 20:24
Duplicate of https://github.com/docker-library/python/issues/933, so https://github.com/docker-library/python/issues/933#issuecomment-2195285004

**Closed** 2024-10-23 20:27 UTC
