### ISSUE TITLE
Missing packages after switch to bookworm / removal of buster

### ISSUE THREAD

**Issue by jesuisnaz** [docker-library/python#836] opened 2023-06-15 07:50 UTC
Greetings! We've been using `python3.8-slim` image for our projects. This morning we discovered that our deployment pipeline no longer works because many packages seemed to be missing.

The issue started appearing after the switch to bookworm. 
I might be missing something, but is there some way to switch back for some time to the older image until it's resolved? It seems to be reasonable. Thank you.
```
Package ttf-ubuntu-font-family is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

Package ttf-unifont is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  fonts-unifont

Package xfonts-cyrillic is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source

E: Package 'ttf-unifont' has no installation candidate
E: Package 'xfonts-cyrillic' has no installation candidate
E: Package 'ttf-ubuntu-font-family' has no installation candidate

E: Package 'python-dev' has no installation candidate
The command '...' returned a non-zero code: 100
```

**Comment by jesuisnaz** [comment] 2023-06-15 08:04
For now, switching to `3.8-slim-bullseye` seems to be doing the trick.

**Comment by ad-m-ss** [comment] 2023-06-15 08:43
@jesuisnaz Based on the fact that the issue is related to the distribution version and the package is not associated with Python, it's worth considering whether this is a problem with a Debian image rather than a Python image. Could it be that the Debian maintainers are responsible here?

**Comment by mpgreg** [comment] 2023-06-15 09:20
Same issues.  GLIBC is missing or something.  

```# /usr/local/bin/python3.8 -m venv /home/astro/.venv/dbt
/usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/python3.8)
/usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libm.so.6: version `GLIBC_2.35' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
/usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.33' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
/usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.32' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)
/usr/local/bin/python3.8: /lib/aarch64-linux-gnu/libc.so.6: version `GLIBC_2.34' not found (required by /usr/local/bin/../lib/libpython3.8.so.1.0)```

**Comment by mpgreg** [comment] 2023-06-15 09:21
Reset to 3.8.16 resolves the problem for me.

**Comment by yosifkit** [comment] 2023-06-15 16:51
If you are having issues with the new `bookworm` based images, then switching to the `*-bullseye` images is the correct workaround. There is likely little we can do to help you transition from `bullseye` to `bookworm`; this is the regular square wheel Debian Stable update that often requires users to reassess which packages they install and ensuring that distribution release matches across used images.

---

> Same issues. GLIBC is missing or something.

I am unable to reproduce. Are you perhaps trying to move that `venv` to a different container or mounting it from elsewhere? If you are moving it across images, then it will need to have the same base libc available -- easiest way is to match distribution release, i.e. Debian Bookworm or Debian Bullseye.

```console
$ docker run -it --rm --platform linux/arm64/v8 python:3.8-bookworm bash
root@74945d174d36:/# /usr/local/bin/python3.8 -m venv /home/a/.venv/d
root@74945d174d36:/# ls -l /home/a/.venv/d/
total 16
drwxr-xr-x 2 root root 4096 Jun 15 16:45 bin
drwxr-xr-x 2 root root 4096 Jun 15 16:45 include
drwxr-xr-x 3 root root 4096 Jun 15 16:45 lib
lrwxrwxrwx 1 root root    3 Jun 15 16:45 lib64 -> lib
-rw-r--r-- 1 root root   76 Jun 15 16:45 pyvenv.cfg
root@74945d174d36:/#

**Comment by yosifkit** [comment] 2023-07-20 21:34
Closing; Solution is to use the `-bullseye` tagged images to stay on the older release. The Debian Bullseye based images will continue to be maintained/updated until the respective Python end of life or the next Debian release, Debian Trixie.

**Closed by yosifkit** 2023-07-20 21:34 UTC
