### ISSUE TITLE
ipv6 parsing of ssh:// without port is broken on python3.8

### ISSUE THREAD

**Issue by fruch** [docker-library/python#517] opened 2020-09-14 06:13 UTC
`splitnport` is now deprecated, and in python3.8 we should port variable from `urlparse`
seem like it now drop the `]` from ipv6 address when port isn't defined

```
>>> from urllib.parse import splitnport, urlparse
>>> d = six.moves.urllib_parse.urlparse(s)
>>> splitnport(d.netloc)
<stdin>:1: DeprecationWarning: urllib.parse.splitnport() is deprecated as of 3.8, use urllib.parse.urlparse() instead
('centos@[2a05:d018:eb8:3100:6c7:522:f7b1', None)
>>> s = 'ssh://centos@[2a05:d018:eb8:3100:6c7:522:f7b1:864d]:22'
>>> d = six.moves.urllib_parse.urlparse(s)
>>> d
ParseResult(scheme='ssh', netloc='centos@[2a05:d018:eb8:3100:6c7:522:f7b1:864d]:22', path='', params='', query='', fragment='')
>>> splitnport(d.netloc)
('centos@[2a05:d018:eb8:3100:6c7:522:f7b1:864d]', 22)
>>> d.port
22
```

**Comment by tianon** [comment] 2020-09-17 21:19
Your example isn't something we can easily test properly (`six` is not defined) -- do you have a minimal reproducer we can run to test this?

**Comment by tianon** [comment] 2020-09-17 21:22
(Also, it would be helpful to have some information about what makes you believe this is a bug in the Docker image, and not something in Python itself -- perhaps an example of a test you've run on a host install of a similar Python version that does what you expect?)

**Comment by tianon** [comment] 2020-09-17 21:25
Reading https://docs.python.org/3/library/urllib.parse.html#module-urllib.parse, this seems to be working as designed?

> | `port` | Port number as integer, if present | `None` |

**Comment by wglambert** [comment] 2020-09-30 15:56
Closing since this seems to be working as intended and if it is an issue maybe upstream would be the more relevant party

**Closed by wglambert** 2020-09-30 15:56 UTC
Labels: question
