### ISSUE TITLE
Both python 2.7.9 and 2.7.13 are installed in the latest python:2.7 image

### ISSUE THREAD

**Issue by Norgg** [docker-library/python#174] opened 2017-02-01 15:33 UTC
We have a container based on python:2.7 running uwsgi, which has stopped working from a clean build at some point recently, with uwsgi failing to import datetime. Haven't been able to track down exactly why, but I'm heavily suspecting it's because python 2.7.9 is installed as `/usr/bin/python` and 2.7.13 is installed as `/usr/local/bin/python` and that uwsgi is somehow using the binary from one with the libraries from the other:

```
$ docker run python:2.7 /usr/bin/python --version
Python 2.7.9

$ docker run python:2.7 /usr/local/bin/python --version
Python 2.7.13
```

**Comment by ushuz** [comment] 2017-02-08 06:27
@Norgg `/usr/bin/python` is the Python 2.7.9 bundled with Debian, the base image of the python image. This is not a bug. Use `/usr/local/bin/python` explicitly in your application.

**Comment by patrickdepinguin** [comment] 2018-01-11 08:41
I have the same issue. When installing python packages via apt-get, they get installed with prefix /usr, while when using pip they are installed with prefix /usr/local.

I don't find reference to this in the documentation/readme of the docker image, while it is important information.

**Comment by ushuz** [comment] 2018-01-11 09:20
@patrickdepinguin 

It's not a Docker image problem. It's how `apt-get`, `pip` and their ecosystem work. 

FYI, `apt-get` installs **Debian packages** maintained by Debian maintainers into `/usr` prefix. The prefix is actually determined by the maintainer who packed the package. 

While, `pip` installs **Python packages** provided by PyPI into the same prefix where `pip` is installed. In this image, `python` and `pip` are both installed into `/usr/local` prefix.

**Comment by alex-left** [comment] 2018-04-18 15:34
I think this is a problem of the image. It's simple, is in the image where I must fix the problem (removing in the dockerfile the wrong python and link it to the correct ).
```RUN apt purge -y python* && \
    rm -rf /usr/bin/python && \
    ln -s /usr/bin/local/python /usr/bin/python 
```
It's unexpectable that a container haves two diferents versions of the same program in the standard and expected $PATH. So, debian team install by default his maintained version of python? that's ok. We must adapt it!. Each distro works in diferent way and do diferent things,  this is not a valid reason to not make the right things. And the right way is: a container only should have unique version of a program.

**Comment by tianon** [comment] 2018-04-18 17:12
There are a lot of utilities within Debian itself that use that system
Python, and they'll likely break or misbehave if we replace it with ours,
which is why we don't do this.

**Comment by alex-left** [comment] 2018-04-19 08:40
Yes, the intention of the snippet is to use it at the end of dockerfile, at least after the required operations at system level. This is necessary because you may have situations with apps that try's to use /usr/bin/python by default, not always you can have control over that. I detect this problem because I use docker to manage multiple version and environments of Ansible. 

Of course, if the container use system features over debian's python, you should keep it in mind, but in most cases can be made it installing all neccesary dependencies in the custom python.

Other solution, probably more simple, is use the alpine image.

**Comment by wglambert** [comment] 2018-05-21 23:29
Closing since issue is resolved

**Closed by wglambert** 2018-05-21 23:29 UTC
Labels: question
